### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by Suleman-Elahi** [bmmlms/whatsmissing#1]
![image](https://user-images.githubusercontent.com/24384996/189322192-e9385152-c316-42d4-a042-82aab3ffc3ce.png)

https://www.virustotal.com/gui/file/382a4ed54773b5ac4a27e9a817601093e068af636c58b13b8ebd58b9c2fa7507

Is there something you can do about it?

**Comment by bmmlms** [comment]
I tried some things but could not get those AVs happy. An easy way would be to use a commonly used installer like Inno Setup or NSIS.

**Comment by bmmlms** [comment]
...

**Comment by bmmlms** [comment]
LZMA compression was removed from setup in the newest release. Should be solved.
